# Generated by Django 3.0.4 on 2020-03-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_borrowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('returned', models.BooleanField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.book')),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.library')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='univ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.university'),
        ),
        migrations.CreateModel(
            name='library_contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_copies', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.book')),
                ('lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.library')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='univ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.university'),
        ),
        migrations.CreateModel(
            name='librarian_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('library_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.library')),
            ],
        ),
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('librarian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.library')),
            ],
        ),
    ]
